---
- name: Ensure the osx_hostname is set
  set_fact:
    osx_hostname: "{{ inventory_hostname }}"
  when: osx_hostname is not defined

- name: Load current hostname
  shell: scutil --get {{ item }}
  register: current_hostnames
  changed_when: False
  with_items:
    - ComputerName
    - HostName
    - LocalHostName
  ignore_errors: True

- name: Ensure correct hostname
  shell: scutil --set {{ item.item }} {{ osx_hostname }}
  with_items: "{{ current_hostnames.results }}"
  when: item.stdout != osx_hostname
  become: True
