---
- name:  Set local ruby version to install gems
  shell: eval "$(rbenv init -)"; rbenv local {{ ruby_version_for_gem_install }}
  changed_when: false

- name: Ensure gems are installed
  gem:
    name: "{{ item }}"
    state: latest
    user_install: no
    executable: "{{ rbenv_rubies_root }}/shims/gem"
  with_items: "{{ rbenv_rubies_ruby_gems }}"
  ignore_errors: yes

- name: Unset local ruby version
  shell: eval "$(rbenv init -)"; rbenv local --unset
  changed_when: false
