---
- name: 'Ensure the path for the credentials repo is set'
  set_fact:
    ansible_repos_credential_repo_path: "/Users/{{ ansible_user_id }}/workspace/ansible-dev-mac-credentials"
  when: ansible_repos_credential_repo_path is not defined

- name: 'Ensure the path for the main repo is set'
  set_fact:
    ansible_repos_main_repo_path: "/Users/{{ ansible_user_id }}/workspace/ansible-dev-mac"
  when: ansible_repos_main_repo_path is not defined

- name: 'Ensure the credentials repo is cloned'
  git:
    repo: "{{ ansible_repos_credential_repo_url }}"
    dest: "{{ ansible_repos_credential_repo_path }}"
    force: no
    update: yes
    accept_hostkey: yes

- name: 'Ensure the dev-mac repo is cloned'
  git:
    repo: "{{ ansible_repos_main_repo_url }}"
    dest: "{{ ansible_repos_main_repo_path }}"
    force: no
    update: yes

- name: 'Ensure that the vault password file exists'
  copy:
    src: "{{ playbook_dir }}/vault_password.txt"
    dest: "{{ ansible_repos_main_repo_path }}/vault_password.txt"
    owner: "{{ ansible_user_id }}"
    mode: 0400
