---
- name: Ensure tmux is installed
  homebrew:
    name: tmux

- name: Ensure dependencies for tmux are installed
  homebrew:
    name: "{{ item }}"
  with_items:
    - reattach-to-user-namespace
    - fzf

- name: Ensure the tat script is installed
  template:
    src: tat.j2
    dest: /usr/local/bin/tat
