---
- import_tasks: variables.yml

- name: Ensure the directory for the iterm preferences exists
  file:
    dest: "{{ iterm_preferences_path }}"
    state: directory
    owner: "{{ iterm_preferences_user }}"

- name: Ensure that the preferences repo is up to date
  git:
    repo: "{{ iterm_preferences_repo }}"
    dest: "{{ iterm_preferences_path }}"
    update: True
    force: True
    accept_hostkey: True
  notify: 'restart cfprefsd'

- name: Ensure correct permissions for the preferences
  file:
    path: "{{ iterm_preferences_path }}"
    mode: "{{ iterm_preferences_dir_mode }}"
    owner: "{{ iterm_preferences_user }}"
    recurse: True
