---
- name: "Ensure the secret {{ dev_secret.name | default('') }} exists"
  template:
    src: secret.j2
    dest: "{{ dev_secret.file }}"
    mode: "{{ dev_secret.mode | default('0600') }}"
  vars:
    the_secret: "{{ hostvars[inventory_hostname][dev_secret.identifier] }}"
