---
- name: Ensure the user for plug is set
  set_fact:
    vim_plug_user: "{{ __vim_plug_user }}"
  when: vim_plug_user is not defined

- name: Ensure plugin path for plug is set
  set_fact:
    vim_plug_plugins_path: "/Users/{{ vim_plug_user }}/.vim/plug"
  when: vim_plug_plugins_path is not defined

- name: Ensure plug autoload path is set
  set_fact:
    vim_plug_autoload_path: "/Users/{{ vim_plug_user }}/.vim/autoload/plug.vim"
  when: vim_plug_autoload_path is not defined

- name: Ensure the name for the vimrc is set
  set_fact:
    vim_plug_vimrc_file_name: "{{ _vim_plug_vimrc_file_name }} "
  when: vim_plug_vimrc_file_name is not defined  


- name: Ensure the path to the vimrc is set
  set_fact:
    vim_plug_vimrc: "/Users/{{ vim_plug_user }}/{{ vim_plug_vimrc_file_name }}"
  when: vim_plug_vimrc is not defined  
